# Generated by Django 3.2.9 on 2022-11-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nm_material', models.CharField(max_length=100)),
                ('unidade', models.IntegerField(default=0)),
                ('preco_compra', models.DecimalField(decimal_places=2, default='0,00', max_digits=6, verbose_name='Preço')),
                ('tipo', models.CharField(blank=True, max_length=28)),
                ('validade_ca', models.DateField(default='DD/MM/YYYY', null=True, verbose_name='Data da Compra')),
                ('localizacao', models.CharField(default='GUANABARA', max_length=100, verbose_name='Local da Compra')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('CARTÃO_CREDITO', 'Cartão de credito'), ('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix')], default='Cartão de Credito', max_length=30, verbose_name='Tipo de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('quant', models.IntegerField(verbose_name='Quantidade')),
                ('quant_minima', models.IntegerField(verbose_name='Quantidade Minima')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quant', models.IntegerField(verbose_name='Quantidade')),
                ('desconto', models.FloatField(verbose_name='Desconto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
