# Generated by Django 3.2.9 on 2022-11-10 03:54

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoquevenda', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiais',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Inserir preço de compra do produto', max_digits=6, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='materiais',
            name='tipo',
            field=models.CharField(blank=True, default='INGREDIENTE', max_length=28),
        ),
        migrations.AlterField(
            model_name='materiais',
            name='unidade',
            field=models.CharField(choices=[('1_litro', '1_LITRO'), ('2_litro', '2_LITRO'), ('600_Ml', '600_Ml'), ('300_Ml', '300_Ml'), ('300_Ml', '300_Ml'), ('200_Ml', '200_Ml'), ('100_Ml', '100_Ml'), ('1_KILO', '1_KILO'), ('3_KILOS', '3_KILOS'), ('5_KILOS', '5_KILOS'), ('10_KILOS', '10_KILOS'), ('100_g', '100_g'), ('200_g', '200_g'), ('300_g', '300_g'), ('500_g', '500_g'), ('1_un', '1_un'), ('2_un', '2_un'), ('3_un', '3_un'), ('5_un', '5_un'), ('10_un', '10_un')], default='500_GRAMAS', max_length=300),
        ),
        migrations.AlterField(
            model_name='materiais',
            name='validade_ca',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Inserir data neste formato: <em>DD/MM/YYYY</em>.', null=True, verbose_name='Data da Compra'),
        ),
    ]
