# Generated by Django 3.2.9 on 2022-11-10 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão da Atividade')),
                ('priority', models.BooleanField(default=False, verbose_name='Prioridade')),
                ('date_conclusao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Atividade')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
