# Generated by Django 3.2.9 on 2022-11-10 01:45

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Cliente')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('idade', models.IntegerField(null=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], null=True)),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Endereço')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço Cliente',
                'verbose_name_plural': 'Endereço Clientes',
            },
        ),
    ]
