# Generated by Django 3.2.9 on 2022-11-10 01:45

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_cliente', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info_cliente',
            fields=[
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('cep', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idade', models.IntegerField(null=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], null=True)),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('id_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cliente_requests_created', to='clientes.cad_cliente', verbose_name='Nome Cliente')),
                ('ds_endereco', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Endereço')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
